# Generated by Django 4.2.6 on 2025-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('vapi', 'Vapi'), ('retell', 'Retell')], max_length=10)),
                ('agent_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('voice', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
