# Generated by Django 4.2.6 on 2025-04-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='description',
            new_name='firstMessage',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='voice',
        ),
    ]
