# Generated by Django 4.2.6 on 2025-04-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_agent_voice_agent_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='speed',
        ),
    ]
